apiVersion: v1 
kind: ConfigMap
metadata: 
  name: catalogue
  namespace: roboshop
  labels:
     project: roboshop
     app: catalogue
     tier: backend  
data:
 MONGO: "true" 
 MONGO_URL: {{ .Values.configmap.MONGO_URL }}